### PR TITLE
Update dependency away from insecure hoek

### PR DESCRIPTION
**Pull request by ShadSterling**

### CODE REVIEW

**Comment by ShadSterling** [comment]
The tests pass locally, I'm not sure from the log why it's different in Travis.

**Comment by hueniverse** [comment]
Not gonna happen. I don't support version 3.

**Comment by ShadSterling** [comment]
I figured, which is why I did the work.  (Or tried to, I still don't understand the travis error.)  It's better to do a little work here than a lot more work in all of the dependents.

**Comment by hueniverse** [comment]
Sorry but I am not publishing a new patch of an unsupported version.

**Comment by hueniverse** [comment]
This is not about time and money. It is the principal that once someone declare a version as no longer supported, it is the responsibility of those using it to upgrade. The same way you cannot get patched versions of node v0.8, no matter if the issue is security.

But this goes further to the issue of my code, especially hawk and hoek, included with the request module but with practically no one using the actual functionality. I know it is not your fault that request still includes this and refuses to remove it. But it is also not my fault. You might think this is such a tiny request but I really had it with people asking for me to support software they are NOT EVEN USING, just to make their build process happy.

My guess is, you are not a hawk user. Which also means, this security grand standing is hollow because if you are using request without using hawk features, you are never invoking the hoek calls that might contain a security issue. The bottom line is, this is not actually a security risk, just an annoying warning.

Writing this response took longer than the effort it would have taken to publish a new version. Like I said, this one is not about time or money. It is about putting my foot down and saying no.

However, if you are actively using hawk in your application, and can explain to me what is stopping you from upgrading to at least version v6 (i.e. not v7 because you cannot move to async yet), I will gladly provide a patch because I do actually care about my users. Those who actually use my code, not just download it.

**Comment by ShadSterling** [comment]
I have a dependency tree maybe 10 levels deep, in a project I am responsible for but have done a small part of the work on.  I tried every way I could think of to upgrade away from the vulnerability, but since I only control the root of the tree there was no way to do that.  So I took it as my responsibility to fix the problem in the way that would affect the most users, in the most leafward package that hasn't upgraded.

I'm not using hawk directly, but when it's buried in my dependency tree I have no way to know that it's never invoked by the dependencies in between.  Nor did I have any way to know that request is depending on an unsupported version - it's not [deprecate](https://docs.npmjs.com/cli/deprecate)d, and there's no indication in the branch's readme.  Who's responsibility is that?

You're not going to convince me that the principle of not supporting something that no-one can tell is unsupported is more important than the principle of keeping people as safe as you reasonably can.  Especially when making that argument is more expensive than increasing security.  I expect I've wasted far more time on this than you have, and now I'll waste more time making a similar pull request to request, which I expect will be met with equally pointless refusal.

**Pull request closed without merging**
