### PR TITLE
Fix minor DoS attack on long headers or uris.

### PR DESCRIPTION
**Pull request by remy**
Replaces #170

This PR, which is really just this [commit](https://github.com/hueniverse/hawk/commit/ccebde4b24d06014ac573888a21813b29a4a16c7) fixes the DoS attack that was merged into 4.x code, but applies it to the 3.x code. 

This seemed important specifically because [request](https://npmjs.org/request) relies on hawk@3.x and have [said they're not ready to drop node < 4 support](https://github.com/request/request/issues/2020) (which would come via hawk@4).

So this patch will offer a 3.1.x version that has the vuln fixed, which should allow request to update their dependencies.

This particular [patch](https://github.com/Snyk/vulndb/tree/3997877197b75c7e41c9eac1825040cf2246597b/data/npm/hawk/20160119) was generated for [Snyk](https://snyk.io) users, but we'd rather see users be able to do updates over patches in their remediation.

I hope this patch will be considered and merge (for release to 3.1.3). Thanks!

### CODE REVIEW

**Comment by remy** [comment]
Note: the linting errors were failing at the checkout point of https://github.com/hueniverse/hawk/commit/66dd8f9b32058c2e834b0976b2f112e19f38ee72 - which is why the build is failing. I've only focused the changes on the vulnerability patch, and happy to take advice to get the build fully passing (or if you're happy to go without the linting checks?).

**Comment by hueniverse** [comment]
You need to also port the tests.

**Comment by remy** [comment]
By "port the tests" what exactly are you referring to? The failing lint that was inherited from the previous commit (which is why the test is failing) or something else?

**Comment by gergoerdosi** [comment]
The tests from this commit ("errors on uri too long", "errors on header too long", etc): https://github.com/hueniverse/hawk/commit/0833f99ba64558525995a7e21d4093da1f3e15fa#diff-ad3c25167d0354b9b277e3ab6f375274R1000

**Comment by remy** [comment]
Perfect, will do.

**Comment by remy** [comment]
Extra tests included and coverage back to 100% (also cleaned up `lib/client.js` to fix linting fails).

**Comment by landau** [comment]
Thanks for the work, @remy @hueniverse !

**Pull request merged**
