### PR TITLE
Pass request to credentials function 

### PR DESCRIPTION
**Pull request by baranguan**
Pass request to credentials function to allow the usage of Passportjs `passReqToCallback: true`
 option in passport-hawk if requested.

### CODE REVIEW

**Comment by hueniverse** [comment]
Why do you need the request object? I'm inclined not to add this option.

**Comment by baranguan** [comment]
I use Passport strategies to the different auth types and as you can see in [Passport Authorization](http://passportjs.org/docs/authorize), they support to pass the request object to the callback in order to be able to use other parameters in addition to the id passed through the bewit. In my case I use the context to retrieve customer information that is necessary to obtain the user with the id.

**Comment by hueniverse** [comment]
I'll leave this open for now, but don't expect this to be merged in the next few weeks. I don't want to support this but I'll give it more thought.

**Comment by baranguan** [comment]
Ok! Anyway could you explain me the possible drawbacks in terms of security or performance, if any, of adding it? Maybe I missed something... Thank you! :)

**Comment by hueniverse** [comment]
It's not really about anything specific, just that I don't like the pattern of using stuff from the request to make these lookup decisions. It's not a feature I would use and as a general rule I tend to focus on my own use cases. Something about time and money... :-)

**Comment by baranguan** [comment]
Ok, I can understand you... Thanks for the explanation!

**Pull request closed without merging**
