### PR TITLE
Fix minor DoS on 3.1.x version

### PR DESCRIPTION
**Pull request by remy**
Firstly: I couldn't seem to create this PR without it including https://github.com/hueniverse/hawk/commit/66dd8f9b32058c2e834b0976b2f112e19f38ee72 - I think it's because it doesn't exist on master, nor any other active branch, so I _think_ this PR might need some tweaking to make it into a release.

This PR, which is really just this [commit](https://github.com/hueniverse/hawk/commit/ccebde4b24d06014ac573888a21813b29a4a16c7) fixes the DoS attack that was merged into 4.x code, but applies it to the 3.x code. 

This seemed important specifically because [request](https://npmjs.org/request) relies on hawk@3.x and have [said they're not ready to drop node < 4 support](https://github.com/request/request/issues/2020) (which would come via hawk@4).

So this patch will offer a 3.1.x version that has the vuln fixed, which should allow request to update their dependencies.

This particular [patch](https://github.com/Snyk/vulndb/tree/3997877197b75c7e41c9eac1825040cf2246597b/data/npm/hawk/20160119) was generated for [Snyk](https://snyk.io) users, but we'd rather see users be able to do updates over patches in their remediation.

I hope this patch will be considered and merge (for release to 3.1.3). Thanks!

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Thanks @remy, exactly the issue we're having!

**Comment by hueniverse** [comment]
Use https://github.com/hueniverse/hawk/tree/v3.1.x instead of master

Also, note that this doesn't affect any request user. It could affect people using hawk on the server to protect services but not anyone using it to make requests.

**Comment by remy** [comment]
When making the PR, github was only listing master as the merge target
(which I appreciate isn't where you want the code to go). Am I missing
something?

**Comment by landau** [comment]
I need this on server. :) +1

**Comment by remy** [comment]
@hueniverse I've created https://github.com/hueniverse/hawk/pull/171 against the new tree/v3.1.x branch and thaat's correctly giving me a single commit. I'll close this PR in favour of that new PR.

**Pull request closed without merging**
